alias egrep='egrep --color=auto'
alias ff='find -iname'
alias fgrep='fgrep --color=auto'
alias g='grep -ir --color'
alias gowork='cd ~/projects/workspace'
alias grep='grep --color=auto'
alias hisg='history | grep '
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias psg='ps -ef | grep '
alias vim='vim -p'
